const LABELS = {
  // cex
  "UQDYM0YvFy2-1J4vTsn_GKUx8UKBCvs2A5QKJt8wVTXqhsK0": { name: "Binance Cold", kind: "cex" },
  "UQCiErgR_u2U30EI2G5RzLfLANOhzOz8jXU5K2bkVOtczTcP": { name: "Binance Cold", kind: "cex" },
  "UQAPykgBUhbI2Fz_JNhT89NhT8HTKSw3Im32EipXtqLSIkmt": { name: "Binance Cold", kind: "cex" },
  "UQDQKawuKNAAC6NJuiBsnyr8ewqCLuFmYWavUoP7BIVxAmVC": { name: "Binance Cold", kind: "cex" },
  "UQDmTo2Aun0l40gEng6BiidXALpwEdAOdxNzHOGYQ3p5x5Sj": { name: "Binance Cold", kind: "cex" },
  "UQCJGVn5fz2lGruG3QUfKhU07MvKHEhxQhzheiyvSFlraxwP": { name: "Binance Cold", kind: "cex" },
  "UQDEYl2dmHSU2pvoSE8CS-PwkjGNcrq3A6v-B7X6Ly44OcE1": { name: "Binance Cold", kind: "cex" },
  "UQCEfvjUxopnkTkFfAR9LEvQhwEm_1CEOTUWausV2BfnTcUy": { name: "Binance Cold", kind: "cex" },
  "UQArhe9wZz4NYlLdaJHJHX70fxUKhUlmAP2t1nSGcf2k3Sw3": { name: "Binance Cold", kind: "cex" },
  "UQD4uGNdB4a3f52mYOZf0x1nCmdd1DAvrLppL0a1cetTYCQx": { name: "Binance Deposit", kind: "cex" },
  "UQDKHZ7e70CzqdvZCC83Z4WVR8POC_ZB0J1Y4zo88G-zCSRH": { name: "Binance Hot Wallet", kind: "cex" },
  "UQCOkbUDgcNt1CrM21H1y12WhIVotJJPgHmxpa5-EPQ-2iNl": { name: "Binance Hot Wallet 2", kind: "cex" },
  "UQDNVsqiDSHhUKPCp6tf0kRXvYpGkXaKmNtXKJ5nxiUPqRD0": { name: "Bitget Cold", kind: "cex" },
  "UQDJlZqZfh1OQ4PY2ze4bSEBznjc8fGzkE2YiP5XLvDv1JNr": { name: "Bitget12", kind: "cex" },
  "UQCi-sp63-vVxZcBCNH3kGXO8ysMFD-xNIkGa2hM3X7pXCoH": { name: "BitMart", kind: "cex" },
  "UQA81a1UsZCnHKq5hLDyEON0LH8hR7fpBzN318a0cAFzYham": { name: "Bitrue", kind: "cex" },
  "UQDWdAIXTL-GTQVwruXCqfgQXzlaeZ3mw5L1hj6vhYarDJmR": { name: "bybitsend.ton", kind: "cex" },
  "UQBsU82HzA0zSG20LBx_wD366y97gVr8NoqxruVn7do_cicK": { name: "Coinspot", kind: "cex" },
  "UQAj7vKLbaWjaNbAuAKP1e1HwmdYZ2vJ2xtWU8qq3JafkaGA": { name: "CWallet", kind: "cex" },
  "UQDXgkYbrxDpRZD6PUZd0jwdjZmYYQd7l5YOE2UeXunLD5hj": { name: "exmo.ton", kind: "cex" },
  "UQDdUoUFrxXG5SBr3Y9smjtUH4DKmK6KUGarP_jeH_XmeM3K": { name: "Farhad Exchange", kind: "cex" },
  "UQC0lrj3O0af8GotieYsTXChA_wijIIVN7Sd_wkgYLwoHxMv": { name: "Gate.io", kind: "cex" },
  "UQCFr3jo0DXpIBF82mVGFc3zcdRkSAtinhENPFMQ2FqzYv0E": { name: "Huobi", kind: "cex" },
  "UQBVXzBT4lcTA3S7gxrg4hnl5fnsDKj4oNEzNp09aQxkwmCa": { name: "Huobi Deposit", kind: "cex" },
  "UQChSx9FI4Wyu5hK0sREHh0jyuBx_fwJbfulPrujtv8dEIro": { name: "lbank.info", kind: "cex" },
  "UQDg5iDIqj8O4xHM0rsL26Vo_a4OKZnblc_EI6LJ37kRC1AC": { name: "lbank.info Cold", kind: "cex" },
  "UQDYh9Di0cT8QSbnHJcNM6sYlpQAAOrnA7sats7Mgwd344Mm": { name: "MEXC 3", kind: "cex" },
  "UQBmoechltZNb69I-ksuqGH2ewSE0tFKWcr3AdjChs5E5Uii": { name: "OKX 11", kind: "cex" },
  "UQDn6G2gh0LtkzQ0_-uPCKY8fhAO6ELiX1manL8IkVdKbDEu": { name: "OKX 3", kind: "cex" },
  "UQD5vcDeRhwaLgAvralVC7sJXI-fc2aNcMUXqcx-BQ-OWi5c": { name: "OKX 9", kind: "cex" },
  "UQB_LPN1koEFYocWeuKaAkDTQMFFycDs9CGrwPLpnJQ0U6Gy": { name: "OKX Cold", kind: "cex" },
  "UQBmlAmSmKc6GbesAPi3Pk6i-ooyUPXgFS2LmLv0uTXqP-ei": { name: "OKX Cold", kind: "cex" },
  "UQCgJMAdLq3CtecfGqKY3bJye9kjrDp6BW_MnW_7zwclJQKz": { name: "OKX Cold", kind: "cex" },
  "UQAD8XEJQppmZDZvlTAKopt2E_c-Xbhzt7_vKH98W4qB5HOs": { name: "OKX Cold", kind: "cex" },
  "UQCkdi_s8DUFA1kjX5jrr7oLG0SbVTGK4-Q52Yvdw1cRGfku": { name: "OKX Internal", kind: "cex" },
  "UQDY4-KtVxawZU_Vva7KTOhlhx8Ho0jI0ahyebYT5YuJkYSf": { name: "OKX Internal", kind: "cex" },
  "UQBZsGXF1mJhpTF2YOlu7kdqpqEbdJvcvowNHz2_JCANHCo7": { name: "OMPFinex", kind: "cex" },
  "UQDz9O0JE6tVXQI3RQWPGmxVpJ1Idlk8ub2rH3gKmbGFvHZD": { name: "Paribu", kind: "cex" },
  "UQBwhUXO-PwBGAIllqBWBEphgz6SNhO_cP0eJfAz_v2KPEyB": { name: "Rapira", kind: "cex" },
  "UQA9LLdOBB3wVgRdO6S-9lD5OMVT24bR2rH4C8nCOP4__rPr": { name: "Rapira", kind: "cex" },
  "UQD1BmMYCRqM-1MOxzIQTOOPd4PZKmZ5_8wM4JYLDpTH0GcG": { name: "Wallet in Telegram", kind: "cex" },
  // named
  "UQBxuGMQdXPOnclIZHvCWCioRjvuxh-z19bdSNNoNlmoCp_6": { name: "4815162342.ton", kind: "named" },
  "UQDurRvcWeqmmrTiNVeE9usI-GteWUc6Wg3DSt-anRVwt55g": { name: "66668888.ton", kind: "named" },
  "UQD-67kHZRLcE9JvEORKfAH94pTrHRFPZ8eYqJwWp1Peg-bI": { name: "akhena.ton", kind: "named" },
  "UQCeHnc3vQK-YCkihu2m2R2Kv0GZvLvylzDKJhFzZKc47Fpf": { name: "aleksdoroga.ton", kind: "named" },
  "UQBbDXXrJsnChbh8gmhT4JZZSR0VYnRLT3lz7aO7oJ3_wc2A": { name: "allmyfellas.t.me", kind: "named" },
  "UQBfx4ECQKl5cHPujjvqLLueamflt9D2SAGqe42o7d3I61Vu": { name: "amanitalovers.ton", kind: "named" },
  "UQAbhMWosoxeoXTJi9Tlw09MEjPVvdJe9j0nC6K6ro0d1t87": { name: "amocucinare-rugger.ton", kind: "named" },
  "UQB9vLBc17hdgqY_I2kUOFwniuJJoOLUd89MRDNulh_M4Ib-": { name: "andrei777.ton", kind: "named" },
  "UQC169oN6c1RA_BYXfpu50TS75IgA0YHZH0ZvVR-x_KDiNvW": { name: "anonymous-on.ton", kind: "named" },
  "UQCc5F-tQjJWfiViSEQ6w1Vr1nRDV0Ro9DL1uLAVZrjCJ_eB": { name: "artemdanilov.ton", kind: "named" },
  "UQBO-exEre52asl4aY2cy60JCJAI2jaIKuoT8wz12BlL_ARZ": { name: "arzinja.ton", kind: "named" },
  "UQD3_DcFOFKIIsJRptfGFmDJUWGanOhXi20p7e362j5TboI1": { name: "astropin.ton", kind: "named" },
  "UQBkZrijbjyo1wsZiNyBnMAQfoqMvnIL44X_pCBEgYIJem5M": { name: "avedictator.ton", kind: "named" },
  "UQC8XsyYdZfHlt5AlouQHKkmsNBPi6sWqXLDdVbeqUcrPLOr": { name: "awesome4000.ton", kind: "named" },
  "UQA2IX4k1k0C00xVTqaM0BseL3XDDnGarB3XmT0nmWsBP6Mc": { name: "bahchisaray.ton", kind: "named" },
  "UQD60rXUOJGET9rpBLADdDu9Kmi1lQXGJu7xcNQHERJAb3hQ": { name: "bigchickenbox.ton", kind: "named" },
  "UQAlL_zWmmdpcmkGKO5aftkhsoSWATALlk6ALpUBaCNwou0G": { name: "bilklinton.ton", kind: "named" },
  "UQA9sN0ZpF4pYjvd1ckluiGaOFSiHJYKni-fWZgDHIilfgSb": { name: "bitcoinholer.ton", kind: "named" },
  "UQBPI9thyt_pads2FINIIGxeu06UjYVU4oWpG-nj2GOf5I1d": { name: "bitmit.ton", kind: "named" },
  "UQCDdfdQey3CHxbh8O8IgI917ypx3JDQ8l5tQC2wlGJTWIm2": { name: "boyko.ton", kind: "named" },
  "UQDjOj3Yb6wwZn-ncIYgff6oMTumUvzQh4PMkpEMRmVG87zY": { name: "brilliant-wallet.ton", kind: "named" },
  "UQBvaBP-BlKIi-KKZTq6VndH_LvDil0bix8wQItiMSDUHvp7": { name: "brucewillis.ton", kind: "named" },
  "UQAZjg9gwL2ww2mtSEC88qUIxcOC6jsscE9HCiuIUHcKdpOE": { name: "caneg.t.me", kind: "named" },
  "UQAAgSvOzjuIFf-wrQ2RFOGMpqXAH1gZFcMqER-8ib-M2vVt": { name: "check-hashtag-on-tg.ton", kind: "named" },
  "UQBteWo_N_g4HecK1Oc3giUtJbcflxjnXVB-4r8Jsrz1EgNW": { name: "clusterfuck.ton", kind: "named" },
  "UQDa_T-plbicZOR188te6gp9T1J4XKd7wA7DUMyKCnFMm60U": { name: "coffeemania.ton", kind: "named" },
  "UQD0RwpJa-tLBav4eIATc0Cxcfh3BstB-h9zROzuxiPKDBdL": { name: "cola.ton", kind: "named" },
  "UQD_6ogbrUGlsbYPF_a6Vwkahpmc9_CRtW6RSVQ8GR0gIR-I": { name: "crypto-exch-io-token.ton", kind: "named" },
  "UQCu-kaf7k6Go4l1QpJJADlJKK4vXnZ-2Fco_IKKMaBDX6wc": { name: "cryptoraccoon.ton", kind: "named" },
  "UQBuH4B6vm1wX4BS3m44OcwK0VhKJS8AWlRMdNBlcXWuphzc": { name: "cryptosurfer.ton", kind: "named" },
  "UQCEUvU9mgKdFhdrQfwE7oluEspq64GS2JA0_nSh_aeSLoI7": { name: "dadashzadeh.ton", kind: "named" },
  "UQD9DXp0JtRy3SZmiNWTnEZMa683BpQ6u6DIEFWPZY1WpOe0": { name: "daradofdct.ton", kind: "named" },
  "UQCNLsm0M2DNcDPM_HUNDn5C0Q547osGH40p-HlDn4z5uUc2": { name: "dark-souls3.ton", kind: "named" },
  "UQDyii0B48UvZh0zwtlnrYJ_mVRit7XL8NtbUwB8RjOzFt46": { name: "darkwebsite.t.me", kind: "named" },
  "UQCwARlTUp2YaTf3dxov6xKVGl175AHZRZbX9P6KUO8iwJJ6": { name: "dart.ton", kind: "named" },
  "UQAEzUAgSL7q2bjnA1uV-_oWylxC7OB05QCF1I1ZVtjE6wo4": { name: "davlet-sultanov.ton", kind: "named" },
  "UQDKDnGnWjTxpRh0b9U1PQfGa0mJfzQB-hQIWtIJUZQ4R0Ya": { name: "dictat888.ton", kind: "named" },
  "UQD_qlA_yV-b3lc1Wl2J0TleKOHixwAgKTb5G1Tloi5cUC4u": { name: "dictator-ton-crypto.ton", kind: "named" },
  "UQASH_yC0zwte_zHR0o0T5xvDUhgmDIm1XjXwl9Cp5B-y5Bb": { name: "dictatorcryptoworld.ton", kind: "named" },
  "UQA2iM4k_jZCfGdVa1jRoImoikPxduOn-13a-nSR_RZ4uVK8": { name: "dimachuprakov.ton", kind: "named" },
  "UQD5E14fhdqyyPZw_edYZzTX0M8L-M0cEar6s5OIw6GtkJJ6": { name: "dimoncrypto.ton", kind: "named" },
  "UQBO9MVJ5i1pWLobhvGLTAHnv-o2nBM_Ml8zPVPwiuX2zVNV": { name: "djasus-wallet-ton.ton", kind: "named" },
  "UQD5iAPfdUTQZfGg2poQ04MSMfTeZY2ajtNMTpwYYWj4TMad": { name: "dmitriydictator.ton", kind: "named" },
  "UQC-ftpLejDFwSU0YnmdIR9V2liuMwFsJH8eqzK90d_8VsdA": { name: "dock-master.ton", kind: "named" },
  "UQCK0rzGz_7Cu80kC0_70JTm_dktc0TSKqThN_7yuimFrXah": { name: "donflo.ton", kind: "named" },
  "UQANPRD2zWF4OeHy_YMyYMmGqfF5tudY5sl7bQ6l47CpyjrU": { name: "dorsteinn.t.me", kind: "named" },
  "UQD3gxfZFttrYyKsBqERwmW2r-UlZ3NO0QSY3t4M822wJ06G": { name: "dozzzig.ton", kind: "named" },
  "UQA-ONJOMW4JL4Df_vqkCMFWwZ6iQtvGzv1aXHmcgPqtrO0X": { name: "drew.ton", kind: "named" },
  "UQD0jl7nBceKl_pKo43UoalZe10Tk5UgiXi8Zv8nuzNbugqG": { name: "durovfragment.t.me", kind: "named" },
  "UQBfl7xt1zx5o2yHeKvyqLEHIxzpPxjHYskRqj0WGKcqaZYr": { name: "e_gem.t.me", kind: "named" },
  "UQDhAiVHFVihy7Wc9zyCZcvirKAvgEwaiTmS3_Ro0hwV6efU": { name: "elector.ton", kind: "named" },
  "UQCBu2oiaSh2LF-C-oCSUQwy1-qQlb8_rCU_LjkzAEgExpIA": { name: "ellafis.ton", kind: "named" },
  "UQCeSoHJhXWOSEdcsQzAvvLxr6HBL06REunvt_8fEKHRaTMd": { name: "emigrant.t.me", kind: "named" },
  "UQCO7Cvl2SxBU9Cm5cHAKFrlgmeSpMXV7t1XrrIAADubuSS7": { name: "eugenenzh.ton", kind: "named" },
  "UQCtS4Nu5lKKdmugZQTIlQ7F1aPr_g1-vv79EOdWBAzOId2Q": { name: "euheniya.ton", kind: "named" },
  "UQCPKyjzp2-6iv3bbcKeehe98MHkKQEUBAvfsNNroU0cA8qM": { name: "evelone.t.me", kind: "named" },
  "UQAFhhvvp6DJtAyhriy7j8Elcbar0o7bGUeCA9e4yvC_X-6H": { name: "fight.ton", kind: "named" },
  "UQBMxAros3D4xMWeX-m2VC_AVK9mYj7z7iEWzXxtGa_aMQ4Q": { name: "firstsnow.t.me", kind: "named" },
  "UQAoYuIS9e1pAsAQFFEXVEmKIbdDnKoqjdvJGTFdJwUVFPWL": { name: "flooooodbot.ton", kind: "named" },
  "UQC6X5Vy8ST8Dnn5hVer8yY5xBK-Qm9IHmDgLLsHveRvjxrq": { name: "fond.ton", kind: "named" },
  "UQAVrM3NgOvdXvkA9EGVRbCyt9FkUKpOgVtl5HFNgD_VL0-R": { name: "fordarklord.ton", kind: "named" },
  "UQDffDXFVYDpapNwsHOQ6EIMtEk1E61AeqxaJYW7KtxZRGWe": { name: "francescomontana.ton", kind: "named" },
  "UQAohA09HOFhfXrYaqVNK94__4aa4zwMEeucwlTzCBANENHr": { name: "fuckyouspilberg.ton", kind: "named" },
  "UQD6IRG0h7oMknMjepw43a8rCoyxuCCMs7TXfZdr5FCs1I3a": { name: "fungi.ton", kind: "named" },
  "UQB4EPXZ433Op3X3lTNyl649GxElgULbkEXKm2PX8-nNCl2D": { name: "garbage-address.ton", kind: "named" },
  "UQBW60T7Yk4tpgLCSnq9Hb5NziWo5bsuEd0QhXoPCMKeKMv8": { name: "globalkintek.ton", kind: "named" },
  "UQAMEaPUWp6IK0OPQF-tAjCH4q9hECE4DCu7h53Z1_a1QHsX": { name: "grigoryrasputin.ton", kind: "named" },
  "UQC9_fN7oe8EoftOl5vcI3p1AIAQSKFnuvolC8--DHto19DS": { name: "guaranty.t.me", kind: "named" },
  "UQDqHHfsPoHxyHo79N5vCvFehHVwN5zaRAW4M2XKSPioLeYO": { name: "gulfstream.ton", kind: "named" },
  "UQDjOBrRBcpPwC9YUuF_u0XHEpj7SW37AT5hCOdt5GtnM-hA": { name: "hardworkpaysoff.ton", kind: "named" },
  "UQC6uYNyHpNi1egxuyslDjY3iH6wXBaceUFbUeb9myM5Bo5n": { name: "haruki-murakami.ton", kind: "named" },
  "UQD0BRQt-QdIEbsjuRsMqzDlBkUAEfQixShDECoKEOXRc4eR": { name: "hashtag-on-tele-g.ton", kind: "named" },
  "UQDIsFlvCQskFf5V7y4HhfHFdpkr_eQ2rqx1787Dqx8PrG9-": { name: "hashtag-on-tele-gram.ton", kind: "named" },
  "UQBaCwVfRZjKvm31saKo4QAHdZgdOXnM6c28y8NzSRbC6yvl": { name: "headfucker.ton", kind: "named" },
  "UQBx06oxGmpFCPcwIAGxtC01yX7zf9QjOCLUP_AhDBT0EGv9": { name: "helloqepaaa.ton", kind: "named" },
  "UQDWNjlaECWrFODLfDzMGKqv1oP0YwmvQAIyGrdJl5TEAUPN": { name: "hippyfitness.ton", kind: "named" },
  "UQBYVLzw_-FBOeVouMssuvUyU1DVN4xyn43AXb0U7dq_jKvM": { name: "hodlbitcoin.ton", kind: "named" },
  "UQDGaL0oXC2t1S4_-BCNsh0cHSpcRtDh73fH5JCVic3cWbUA": { name: "honorandrespect.ton", kind: "named" },
  "UQDLmbhZTwJvfBFNu6iacy894-F7k5vAkN6tMOJs-XKiI0h0": { name: "hydroxide.ton", kind: "named" },
  "UQC6yp_TnzUN4FpM975yNk5mWGSLN3W2VF2HzEhSKBS5AuIx": { name: "ilia-mikheev.ton", kind: "named" },
  "UQDksfXjOKX4WHklELwzTOpHDYyjvd_HWOuKPGTl31Y7I6RY": { name: "illuminat.ton", kind: "named" },
  "UQBUKvE-kNJGOLBMknEklrb223QZ_eZ76SQ_7jDfZMn4U2ui": { name: "imlovingit.ton", kind: "named" },
  "UQC6MgWyeYuaxTwKtTW-cPE9sEMAtRKKgfy7ExcRaBylx0rQ": { name: "imverysleepy.ton", kind: "named" },
  "UQAKiflnkg4xGFHeFVKOOq0D8zmRjza6fREZLowI6RvQozQN": { name: "irespect.t.me", kind: "named" },
  "UQCLBw7bAacA8_akYkx-CG4DbahgYOuwTxmQjuYaNTczX2jy": { name: "join-to-souvenir.ton", kind: "named" },
  "UQCA_EVfHdvO8ivCbG3fbGCvqBSEvV3tHpZZZxQZfA7lY6_p": { name: "joooooooooo.ton", kind: "named" },
  "UQAWnIXYX6GyQMnF5DQneSLHlVkoL30U45Ijds1dIkUqK7ZO": { name: "joshua.ton", kind: "named" },
  "UQBq8CQX4zFWx_SGp09S7zOxwowMwgejHhdMc9FjAJaH-U0K": { name: "joydivision.ton", kind: "named" },
  "UQBWsMS7YVJz_V_V0SQ7KROXNPcCi7nZ_cM6uLCw5A1o8Q7K": { name: "kawaii-ing.ton", kind: "named" },
  "UQAzu_uXtCGcSPNhvczI_t58rzsYZEHpikIZqqJgCY3mZ3QB": { name: "kifpool.ton", kind: "named" },
  "UQA-Q8PSIkVWLHfLqG4Seuy5Wr5ZxUDqCG61otvFOW4TNYsQ": { name: "klimofficial.ton", kind: "named" },
  "UQBC1BhH1pARrfeT3NHFHgoocXqz1XidQvipCFx9qCXJ9r0m": { name: "korobko001.ton", kind: "named" },
  "UQDt5-Gf0yBzjX_nG96RTmOAZzOAgdIp35hDiWutrny9x_e9": { name: "krovavyj.ton", kind: "named" },
  "UQAZIjF0naouug8QC2D8xMkV348VBx0rc7wL5G-5wZVqXlpR": { name: "kurumkangaruda.ton", kind: "named" },
  "UQDkNYXyQ9MlV5d9aRO4UAS4vYuXuTXiCPWwbiBw3qCXJn2i": { name: "lifestream.ton", kind: "named" },
  "UQBsQ9Q5Lks_r3BdvAyjnTqpX8bwKlYqJ_e2qJnkY0mexLpP": { name: "liveintonspace.ton", kind: "named" },
  "UQBdFxBeTNEpYSFxj1YDxtWWd2dNqEVRQ765ITGlp0ilZ6FP": { name: "longlife.ton", kind: "named" },
  "UQDbeCMIciXTzYeCb0kHYMCi3KUVPfIHY3d8CY_cUX4rKMNT": { name: "macedonia.ton", kind: "named" },
  "UQAzAm7AVdByF2ih3GpeMXvYXkSLYXykbstwXv1ztCincWvq": { name: "magik.ton", kind: "named" },
  "UQCsAAQoDjtW7E6HzbS8U5cJW5Ub4r1I1e8jr5N1D_9zxKVU": { name: "magvaer-dct.ton", kind: "named" },
  "UQDzW1O6Ct8_G_vKkT44iQhW-AKwp8ZZmUzlb8bCHIsckKs_": { name: "mastergoal.ton", kind: "named" },
  "UQBDPNMTVxfqP_JOVCTMyF1jBcKR1w6jdbypXuCVGRlJx0tA": { name: "memeholder.ton", kind: "named" },
  "UQAVMLNdbHBnp_wq03lxK_DK3Cg6fdS-hMK9NPTRrMQMXSGa": { name: "mexican.ton", kind: "named" },
  "UQA8KeDMombMVb_FsNlppYD6yPUfD-x2VjmejuIOY6rXUgtZ": { name: "mikefromminsk.ton", kind: "named" },
  "UQDthf9KrO4ZYBQzxwgMuYA9GvMBnV3_IArAtHkW01DJZVJ0": { name: "million-mega.ton", kind: "named" },
  "UQDER3GqE2SM3WUbyobUisa14zAaDnMee1f9dS4so-DyEd3t": { name: "millionnft.t.me", kind: "named" },
  "UQCuJNpry3MTSEHFsTItvMfrVg0yeyLqhlgm9iJu5sxpF6bn": { name: "moneyflipin.ton", kind: "named" },
  "UQDj42evrvim0BMENhEL6gNc4gq7Q3JqoyK9NnT0Fawao0Zf": { name: "moonman.ton", kind: "named" },
  "UQCN_txkExD2dfcxRTuCPCtQH1S-XEJ9U1Uj94RzGQ9xtnYB": { name: "nemo-founder.ton", kind: "named" },
  "UQC6UFUUIBEBmE3Y93dufJ0KBxH1aOg7qQA34TqXY9oPb8AL": { name: "nikitadictator.ton", kind: "named" },
  "UQCB1s9MTnuMeDmB9Gw84fUzKDQ_6oNrzWglUlWnib0YyuMD": { name: "niubi.ton", kind: "named" },
  "UQBwxpQd0niY3kjEvUAAPB_ZRMFxCgdMDG_bhqjK98VX8nrO": { name: "not-evangelist.ton", kind: "named" },
  "UQAFN7SIDZlmJupe8Cg6K6AvB18V2M1_vBEntoNHYoLeswbS": { name: "not-not.ton", kind: "named" },
  "UQAvlWFDxGF2lXm67y4yzC17wYKD9A0guwPkMs1gOsM__I5W": { name: "notcoin-minter.ton", kind: "named" },
  "UQAMalEtVI5qTxy5l9yonc5cwapTvB8EubS3cte94t-lmlH8": { name: "notfree.t.me", kind: "named" },
  "UQDUW7ljDvwi2a90wU1LVRobWAQ0CyQcRo1khzExtxTEuGGj": { name: "notfucker.t.me", kind: "named" },
  "UQC_bb8W1l5lvKgtUH8o6GzstKg-5pTHYCWyVEfO0ot0LkDD": { name: "notlove.ton", kind: "named" },
  "UQCZ1hh2gey2XImom9xtTiJEHdTQzBRxMF5b8zC2D3ffjdQl": { name: "notnotcoiner.ton", kind: "named" },
  "UQCU8MAHBuOhn_0TlBgHirjCBdtJr-ag_mjAjYfdjrOUbn9X": { name: "notpaperhands.ton", kind: "named" },
  "UQA2SljtsGsUhgbKZWurNeVe07Q62RW1YUDCufH59Gvb-5CL": { name: "numbe.t.me", kind: "named" },
  "UQCeE47NvxMtaaOp4BYC9qaiwCUviuiHovDbDCKgQNmcNQjm": { name: "numberofgod.ton", kind: "named" },
  "UQDFzBSXoQ2NFopNwL3uHe5BwT99p3uFDq-Tb-hPgkSbl3Yw": { name: "oboronitel.ton", kind: "named" },
  "UQDDPGa-U6cvc2zRveS279fH008D8NolonbgBnAVCR9U_pwm": { name: "onco.ton", kind: "named" },
  "UQBBxrfhEdgRLlvdl5m630mC3yqheL4CRDacVq-h0i0jg2ey": { name: "onemillionexabytespersecond.ton", kind: "named" },
  "UQD0gtzgmJExo-cCPB0o4q3TvhZ0laLvEZ-g21jKSQ6lZPd9": { name: "optimus-princeps.ton", kind: "named" },
  "UQDtqG0vTOaYkhTJMx-XmmopZNaX2jKrPntYHitmURSe02ys": { name: "orionuz.t.me", kind: "named" },
  "UQCexmMrQYjJ8kMxKsDG8BR60XRP7EgYQ-8itL1wRbQurwBr": { name: "overlandoracle.ton", kind: "named" },
  "UQDYzZmfsrGzhObKJUw4gzdeIxEai3jAFbiGKGwxvxHinf4K": { name: "Pavel Durov", kind: "named" },
  "UQBqYvg__AiIZphan7ymlfEVhim-uga2tMNqIoPGPS5a64KN": { name: "pavelpromov.ton", kind: "named" },
  "UQDyX8x4iAfBbhJHugynYGBX1U1dKjRdB2KCCEMlMOj6tPpg": { name: "percivaltrade.ton", kind: "named" },
  "UQCDnkvGku_DcZ8EwY_sZqBPOu8176pk6jD7yW9UzSKd3erZ": { name: "persiancrypto.ton", kind: "named" },
  "UQCt8DH0wLhde6uOiAHbzfIXIka7ixcveW3u4phwTE5SWjnc": { name: "pishro.t.me", kind: "named" },
  "UQC0RRtM5QoxilI2vw6lh4UQ6jmKG9jPwiVnLZ14b_WFXOnH": { name: "porscheswallet.ton", kind: "named" },
  "UQCDQBAJISeYZRgreSyIIWwuxnIFUnVzPeGkbA6se7MBIKOB": { name: "potus.ton", kind: "named" },
  "UQADJ9kq8YJTmXOsafqfHNZyKfm5bDU2cZFZyHTLtZoZqsFM": { name: "premium_news.t.me", kind: "named" },
  "UQADS9zHEIXjODNAibC-3Mp6yRmaswVT3PGkQtMoQe0XtWb0": { name: "premiumname.ton", kind: "named" },
  "UQCNewvgiDZ-UOZ043gCJ4cU1b_iCkCV9idRJDxWMPiv54P2": { name: "promining.ton", kind: "named" },
  "UQDOEDaQDs752LWbxGMbnywEsq18WerRHHKwfowKwqMg7x4x": { name: "qwicu.t.me", kind: "named" },
  "UQCjcDiLiHhpeg0TiAK0dxzTSdgwW5aS1v7be6-mH0C8mgb3": { name: "realspin.ton", kind: "named" },
  "UQAiOw4zLWQa1Siu6XQ8-3JZaMVaxENW7ermJUrtrTEtxv5D": { name: "recrent.ton", kind: "named" },
  "UQBQXhOFz4ZnC17ClV507ac2M3o5IlNhqLZ91pIC4Zmx9UIR": { name: "riocool.ton", kind: "named" },
  "UQAzV79Xy4Rvh9g6HrmLm_xvkOM5xHqwDJuDv6e89m7FAoqt": { name: "rudolfmxxxiii.ton", kind: "named" },
  "UQBAE6s0gc16sdoqgmJJQqakO2dFUS1p2ABxwIzXrd4lVmbx": { name: "runshop.ton", kind: "named" },
  "UQDdceUhaG9Bpx55u-c0XvGoyBH8hogco7SNP0cUJikvCLAs": { name: "russiawallet.ton", kind: "named" },
  "UQAYJ4gGIUDwvlEStjkuZENaoBAQU7pt-Bv4-Pmc7-hibY2W": { name: "samarakovsky.ton", kind: "named" },
  "UQCTp57IatvU5QH1kjFZrJ9Ld8uKPItSdBsztqmJr7wPLFPE": { name: "samosval.ton", kind: "named" },
  "UQCvHUlS7fUOowv37htON9N_yUKV2nk3i7w9Dvbdk5wd17W3": { name: "satoshifriend420.t.me", kind: "named" },
  "UQCD7SKgUnvYMGrDCLCuwIwGvHj3wUfdXXoZ7jQniu6BXY8O": { name: "secret-girl.ton", kind: "named" },
  "UQCBKCesgqQPoIPVplSbdo6FmEIcWxxHKxfqJfTnIE_6jh9C": { name: "secret-room.ton", kind: "named" },
  "UQD9uLIfZaGk9WwOjGEVre4sHVkYdx6_yNvKCQqg8dEs9oUF": { name: "sergeygroup.ton", kind: "named" },
  "UQAfw2P8s63-bfgSEDP9ELiGwIvxKgjwnV32ueF75tF4zFBp": { name: "snoopdoggydogg.ton", kind: "named" },
  "UQDd6oBNjM8GBexiu-77pNcYI77gHKo9Xej--1xiNV8m2MFZ": { name: "sport_insider.t.me", kind: "named" },
  "UQDCABNVX2hIGnr41pW4tg_M0PilYhID_MFDCBEp2g6mBwIu": { name: "sunlight.ton", kind: "named" },
  "UQDkPSCHVaTdwwk2ABhKwgBztThtNiKRiZOKMIJHyMvGEav8": { name: "suppisland.t.me", kind: "named" },
  "UQC9bHyCGAqxjfZadkqwD5x1HGn1704VROH-wTtBvkuOBltr": { name: "takechip.ton", kind: "named" },
  "UQCxVdJF42cDwODx13wamt4SJ7ihgagUOkXCmFDsd7uRn7pW": { name: "targetingads.ton", kind: "named" },
  "UQCPyXQH4s1IIkEtOJOAzlDAmSJLAzzyniEIxvCuJRoesBo7": { name: "theoligarch.ton", kind: "named" },
  "UQBa-PThWxi3sSoTGdiUzYyC1DbfBMvCU-b5xkSzrPjdkcdM": { name: "threads.ton", kind: "named" },
  "UQAhbuA3pMyppJNorHpWtHvz0BQDsRTWdaec6rAq7GXj9AO0": { name: "tonano.t.me", kind: "named" },
  "UQB3Z1Ctcd4Jg231Eshs0hnUSjGPiQ8QFkmzljLgyf_iACLB": { name: "toninvest.ton", kind: "named" },
  "UQAaQRXoGq9Le_BMo4SY1O4DgAEoO2sa1etgeJCR2CLS3lwB": { name: "tonkinside-telega.ton", kind: "named" },
  "UQAm-lwUYbIOKX-GvFft9srnYteYmpUfF05lD_X9o0CfP03K": { name: "tonland.t.me", kind: "named" },
  "UQCCaDhZBx-F7QfRABaxm47NGDkzpGmHrtn9xQLyUNlASl7z": { name: "tonoton.t.me", kind: "named" },
  "UQBt6OVD9eaqzTP80QmZfMOF5GCt8JsricPmWzq8uqcFHM6f": { name: "tower-treasury2.ton", kind: "named" },
  "UQDDBKiuOhSUSayNyVPx24juwdxn2_5ziZMReV6w9UkP77sR": { name: "tradein.t.me", kind: "named" },
  "UQCxlxsm183utGEJCh6ugRv-ocrAosm9FMXIjY8g_plGS2BQ": { name: "triagrutrika.ton", kind: "named" },
  "UQAvGHhcaEhythBpoDuthgeKQ9HC5cDSTSLnFMEQ2DFmwQXC": { name: "tvnetwork.ton", kind: "named" },
  "UQABFuckIRGCTerroristsNOBITEX1111111111111111_jT": { name: "use-ton-dns.ton", kind: "named" },
  "UQBsrGhsBWBL2yDwB2QpOI5oskEx9NWw_9ypmZfijIO3GQvD": { name: "user.vipx.ton", kind: "named" },
  "UQCbp35W3x_AG_JYP2FmbBKm1czPi2L9-BJ-2_r0Em-d5tZ0": { name: "vave.ton", kind: "named" },
  "UQC8g3CJz4NVIyWFYy6RiABriM62V5Om06cvZJ7kB9Z-tykb": { name: "vc-projects.ton", kind: "named" },
  "UQCvVBkvdXjal6VvPuBsU79WErAUqmDPmyCltS21qxnXiUBr": { name: "vg-dct-team.ton", kind: "named" },
  "UQAHPUUjBEAq9ZtRc3Ot1LUoEvu3cRd22BB-7RhpLrXVHHOw": { name: "visit-hashtag-on-t-g.ton", kind: "named" },
  "UQCrbutAkBGsGo5IC9HqJEW-tUVA-T_c1UFvGeG7NB9lLKE8": { name: "visit-hashtag-on-tele-gram.ton", kind: "named" },
  "UQBsJbXy_l7xpqGXj2EfYaUIg_1QoIIrGRdkRfypMYIyY9Ql": { name: "visit-hashtag-on-tele.ton", kind: "named" },
  "UQCCshnretFFgFv_uX9qsDYXStWCLqtSHJoIstnY20yGx-DR": { name: "vpcryptoinvestor.ton", kind: "named" },
  "UQAEfvu4ECAWDShGQSQnFmDRVl2q1n-m-YSk9MEWWG9ZaCPE": { name: "wallet-4you.ton", kind: "named" },
  "UQCnRJV2bdD21Vqbj-TwCLXlgrIp0GuJJrprlCGJWEA_URnk": { name: "wallet-dictator.ton", kind: "named" },
  "UQATChk2BbCGUHcb2tLLuL68Rf1v5Jj28BNp1kcE8LBtxB1Y": { name: "walletalex.ton", kind: "named" },
  "UQDDnfmC8ZFODz-pSspaPmT22XXLAHe9CVxi_84mjkJlW8Cp": { name: "web3-studio.ton", kind: "named" },
  "UQCcMwTG3jOOMb2P3bKJVkCS2ZEWEK-L4agsR6_nOJFicnYE": { name: "web3world.ton", kind: "named" },
  "UQDhj3RqnjANZ2YTisNoeEVP-cRv0NKwqRyDONsA02IgLVd4": { name: "win-to-win.ton", kind: "named" },
  "UQAibp1I8siUULQqtpA5_UfMaIbQJdi7Lg4tafWhj5qumPRK": { name: "wtf-coin.ton", kind: "named" },
  "UQDa_D7S54iEgtfS3nUqnKRQcfeCnwVtAjVFAIaXcSOMHxnG": { name: "wyatt.ton", kind: "named" },
  "UQAlH8tidls2-6lnAq0UDek632J5s_JtcXpM925WuuEHnqc4": { name: "x2maker.ton", kind: "named" },
  "UQALoCwBVMyW6IFZDf5SCILztGSbSm1zydtPHgIS3fORYFKq": { name: "xcorp.ton", kind: "named" },
  "UQC-UbGoWQUY22co_3WCHg-lc3Mx1QLMWDpu34qBEuWAiERc": { name: "xhtmlxenops.t.me", kind: "named" },
  "UQABGo8KCza3ea8DNHMnSWZmbRzW-05332eTdfvW-XDQEmnJ": { name: "xRocket Bot", kind: "named" },
  "UQDXuwZLVXxnlx_mrDn1ZbiK72_MQUx5mC6pLZCvHkJ6ua5O": { name: "xydessa.ton", kind: "named" },
  "UQCoAYGW42Gz972h2RnL-sXHYNnp-KH1yJYPbn6BExMKTOLy": { name: "xyliganka.ton", kind: "named" },
  "UQAH1FlQgFROgfjRL-dWaQKluxoT4g5fFocppHaUdEx1n5JV": { name: "yearqueen.t.me", kind: "named" },
  "UQDWPe35wKdiSLZsBf_SEg1QgVBg-12lPZ5NUzsU7T7syz75": { name: "yeshold.t.me", kind: "named" },
  "UQBrjRt0pc4ujPFbS7MOJQ5MnCfcKVlG6_T4K_FqJigXOUSV": { name: "yourfurer.t.me", kind: "named" },
  "UQD82G_H22R8Zi1XkkY2fCsXDwzO7yzwQ_B_3xF5NUxjRhuh": { name: "yuklov-1981.ton", kind: "named" },
  "UQCZR0Pv5hBc4aLqKqDGpnCug1wlDmfC8_aW05UCx_GPyOod": { name: "zeroperte.ton", kind: "named" },
  "UQAS5Yht5UApZVFabpeA21TolwBuXNulkjLVQdJPed0Uu8aq": { name: "zhdun-derzhun.ton", kind: "named" },
  // protocol
  "UQAJxbmwhwJw-FomFlt1RYukdeTltiCmWlsurQsQMRJhZaqE": { name: "DeDust NOT vault", kind: "protocol" },
  "UQDtU7yZnlpK9po_nD3lN299kMSH4VKPMx5xbb6FkD1REpyy": { name: "Notcoin Royalty", kind: "protocol" },
  "UQAPZauWVPUcm2hUJT9n36pxznEhl46rEn1bzBXN0RY_ynFz": { name: "Notcoin Voucher Swap 0", kind: "protocol" },
  "UQASgm0Qv3h2H2mF0W06ikPqYq2ctT3dyXMJH_svbEKKByVc": { name: "Notcoin Voucher Swap 1", kind: "protocol" },
  "UQArlmP-RhVIG2yAFGZyPZfM3m0YccxmpvoRi6sgRzWnAFDp": { name: "Notcoin Voucher Swap 2", kind: "protocol" },
  "UQA6pL-spYqZp1Ck6o3rpY45Cl-bvLMW_j3qdVejOkUWpOQj": { name: "Notcoin Voucher Swap 3", kind: "protocol" },
  "UQBJ_ehYjumQKbXfWUue1KHKXdTm1GuYJB0Fj2ST_DwORqeY": { name: "Notcoin Voucher Swap 4", kind: "protocol" },
  "UQBRmYSjxh9xlZpUqEmGjF5UjukI9v_Cm2kCTu4CoBn3Xh5G": { name: "Notcoin Voucher Swap 5", kind: "protocol" },
  "UQBkiqncd7AFT5_23H-RoA2Vynk-Nzq_dLoeMVRthAU9RADs": { name: "Notcoin Voucher Swap 6", kind: "protocol" },
  "UQB_OzTHXbztABe0QHgr4PtAV8T64LR6aDunXgaAoihOd0HL": { name: "Notcoin Voucher Swap 7", kind: "protocol" },
  "UQCL-x5kLg6tKVNGryItTuj6tG3FH5mhUEu0xRqQc-kbEjsb": { name: "Notcoin Voucher Swap 8", kind: "protocol" },
  "UQCZh2yJ46RaQH3AYmjEA8SMMXi77Oein4-3lvqkHseIAk07": { name: "Notcoin Voucher Swap 9", kind: "protocol" },
  "UQChKo5IK3iNqUHUGDB9gtzjCjMTPtmsFqekuCA2MdreVBFr": { name: "Notcoin Voucher Swap A", kind: "protocol" },
  "UQC6DNCBv076TIliRMfOt20RpbS7rNKDfSky3WrFEapFt53C": { name: "Notcoin Voucher Swap B", kind: "protocol" },
  "UQDE_XFZOYae_rl3ZMsgBCtRSmYhl8B4y2BZEP7oiGBDhgX3": { name: "Notcoin Voucher Swap C", kind: "protocol" },
  "UQDddqpGA2ePXQF47A2DSL3GF6ZzIVmimfM2d16cdymy2ifW": { name: "Notcoin Voucher Swap D", kind: "protocol" },
  "UQDv0hNNAamhYltCh3pTJrq3oRB9RW2ZhEYkTP6fhj5Btc6r": { name: "Notcoin Voucher Swap E", kind: "protocol" },
  "UQD2mP7zgO7-imUJhqYry3i07aJ_SR53DaokMupfAAobtxg1": { name: "Notcoin Voucher Swap F", kind: "protocol" },
  "UQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4Tnjo": { name: "STON.fi DEX", kind: "protocol" },
  "UQDx--jUU9PUtHltPYZX7wdzIi0SPY3KZ8nvOs0iZvQJd_ng": { name: "STON.fi DEX", kind: "protocol" },
  "UQCDT9dCT52pdfsLNW0e6qP5T3cgq7M4Ug72zkGYgP17tphG": { name: "STON.fi DEX", kind: "protocol" },
  "UQDAPye7HAPAAl4WXpz5jOCdhf2H9h9QkkzRQ-6K5usiuVpH": { name: "STON.fi DEX", kind: "protocol" },
  "UQC_-t0nCnOFMdp7E7qPxAOCbCWGFz-e3pwxb6tTvFmshma8": { name: "TONCO", kind: "protocol" },
};
